### ISSUE TITLE
Can't build on Mac M1 with 11.5.0

### ISSUE THREAD

**Issue by vesparny** [realm/realm-js#5511]
### How frequently does the bug occur?

Always

### Description

Since version `11.5.x` I am unable to run the project on Apple silicon.
Using RN 0.71.3

### Stacktrace & log output

```shell
info Found Xcode workspace "MyApp.xcworkspace"
info Found booted iPhone 13
info Launching iPhone 13
info Building (using "xcodebuild -workspace MyApp.xcworkspace -configuration Debug -scheme MyApp -destination id=F9D05ED7-9D66-4017-B18C-FE9E6B107B6F")
▸ Running script 'Create Symlinks to Header Folders'
▸ Running script 'Create Symlinks to Header Folders'
▸ Running script 'Create Symlinks to Header Folders'
▸ Running script 'Start Packager'
▸ Linking MyApp

❌  ld: symbol(s) not found for architecture arm64



❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)


error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening MyApp.xcworkspace.
```

### Can you reproduce the bug?

Always

### Reproduction Steps

`react-native run-ios`

### Version

11.5.0

### What services are you using?

Local Database only

### Are you using encryption?

Yes

### Platform OS and version(s)

any

### Build environment

Which debugger for React Native: ..
sas

### Cocoapods version

11.5.0

**Comment by stevenmathers** [comment]
well, I dont know about M1, but I am getting a similar error building on App Center, although it builds fine locally on my intel mac mini

xcode version 13.4.1 node version 16, react native 71.3, realm-js 11.5.0

where should I look?

thanks

======

**Undefined symbols for architecture arm64:
"_objc_msgSend$allBundles", referenced from:
realm::copy_bundled_realm_files() in librealm-js-ios.a(platform.o)**

and a bunch more like this...

ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ARCHIVE FAILED

**Comment by superdorvil** [comment]
I'm having this issues as well.

**Comment by vesparny** [comment]
@nirinchev I confirm the issue happens using Xcode 13. Didn't have a chance to try other versions

**Comment by stevenmathers** [comment]
> Is everyone affected by this using Xcode 13? If that's the case, then it is likely related to https://developer.apple.com/forums/thread/716965 as we switched to building the native binaries with Xcode 14 on CI. Based on the comment on the issue, we may need to add `-fno-objc-msgsend-selector-stubs` when building the native binary.
> 
> As a temporary workaround, you can upgrade Xcode to the latest version. @kneth assigning this back to you it's more involved than I hoped. Looks like it's a simple fix, but I don't have anything RN setup to test that it works.

yes, can confirm that simply using xcode 14 on App Center fixed my issue, altho as I said before, I was able to build the identical app on my local machine which has xcode 13 installed, so its not consistent for whatever reason.  Thats all I can say.

**Comment by kneth** [comment]
> can confirm that simply using Xcode 14

Thank you for the confirmation. We will work on a fix and get a release out as soon as possible but if you can, please upgrade to Xcode 14.

**Comment by kneth** [comment]
I have a PR for it in https://github.com/realm/realm-js/pull/5531 but I haven't verified that the artefacts can be used with Xcode 13.

**Comment by kneth** [comment]
Released in v11.5.2

**Comment by vesparny** [comment]
@kneth same issue happening again with xcode 14 and `realm@11.6.0`

**Comment by kneth** [comment]
@vesparny Please create a new issue
