### ISSUE TITLE
toJSON() is not working when upgrading realm from 3.6.4 to latest version 6.1.2

### ISSUE THREAD

**Issue by yksingh12** [realm/realm-js#3255]
## Goals

I have upgraded the version of Realm from 3.6.4 to 6.1.2. I am facing below issues in that:
- Object destructuring is not working
- Object.assign in not working
- toJSON function is not working
-JSON.parse(JSON.stringify(cat)) - this is also not working

## Expected Results

Above problem should not be there in case of upgrade

## Actual Results

TypeError: classObj.toJSON is not a function. (In 'classObj.toJSON()', 'classObj.toJSON' is undefined)

## Code Sample

1.
let classObj = realm.objectForPrimaryKey('FavouriteClasses', tag);
console.log('toJSON() ', classObj.toJSON());

2.
let classObj = realm.objectForPrimaryKey('FavouriteClasses', tag);
let newObj = {...classObj, favourite: someFunction(classObj)}
console.log('newObj ', newObj); /// output => { favourite: true }
This was working fine in Realm 3.6.4

## Version of Realm and Tooling

- Realm JS SDK Version:  6.1.2
- Node or React Native: React Native 0.63.2
- Client OS & Version: iOS 13.4
- Which debugger for React Native: None

**Comment by enigmablue** [comment]
I think its related
https://github.com/realm/realm-js/issues/3138
https://github.com/realm/realm-js/issues/3110

**Comment by steffenagger** [comment]
Hello @yksingh12 

Destructuring & `Object.assign` doesn't work in `realm@6`, due to a change in where the data resides in the prototype chain - you can read more about it in this issue: https://github.com/realm/realm-js/issues/2844 (and please upvote that issue, if you're missing destructuring).

As for `classObj.toJSON` to be `undefined`: Are you using Class Models?
I'm asking because for Class Models, it's recommended to inherit from `Realm.Object`, so my next logical step would be to suggest just that... unfortunately (as @enigmablue also mentions), there's a bug in the current release where `Reflect` doesn't play nice with Realm when Class Models extends `Realm.Object` (see: https://github.com/realm/realm-js/issues/3110) - so it would be unfair of me to suggest you do that, just yet.
This should be fixed in the upcoming versions.

**Comment by yksingh12** [comment]
Hi @steffenagger, 

Thanks for explaining the issue. You are right. I was using the class model based schema without overriding Realm.Object class. I tried to extend my realm model with Realm.Object which also didn't work.

My Schema:

class Pet {}
Pet.schema = {
  name: "Pet",
  properties: {
    tag: "string?",
    name: "string?"
  }
};

This is how I was opening it:
const realm = new Realm({
  schema: [
    Pet
]})


Solution:
I have changed the way of opening the schema:
const realm = new Realm({
  schema: [
    Pet.schema
]})

This is working fine for me. I hope that it will pass the upgrade test on existing database.

**Comment by enigmablue** [comment]
oh i tried the Pet.schema way too but I think I had some trouble with the static as well as class methods so I gave up.
Let me know if you got that to work

**Comment by steffenagger** [comment]
@yksingh12, yes that is the current work-around, and glad to hear that you've found a way forward that works for you (or at least doesn't block you).
One caveat, to be aware of, with this solution, is that you won't actually get an instance of `Pet` from e.g. `realm.objects(Pet)` (As I can see @enigmablue has encountered, while I was writing this).

For this to work as intended, you unfortunately have to wait for the next release.

**Comment by yksingh12** [comment]
@steffenagger What should I do now? Should I revert back to 3.6.4 ?

What If I change all my schema to non-class based ? Will it work this way ?

Please guide me. My app is live on App Store. I don't want to push these changes if they are not stable or could cause any issue in production.

**Comment by steffenagger** [comment]
@yksingh12 I would suggest you wait for `6.1.3`, which should be out one of the following days. That way you wont need to change from using class-models (other than extending your current models with `Realm.Object`).

If you want to change to non-class based, you should ensure that you're not using any instance methods from `Pet` (when returned from Realm) and that you're not doing checks like `someValue instanceof Pet` in your code.

Apologies for the bumpy start with v6.

**Comment by kneth** [comment]
I am closing the issue as we believe is has been fixed.
