### PR TITLE
Allow user to use Xcode 13

### LINKED ISSUE #5511: Can't build on Mac M1 with 11.5.0
### How frequently does the bug occur?

Always

### Description

Since version `11.5.x` I am unable to run the project on Apple silicon.
Using RN 0.71.3

### Stacktrace & log output

```shell
info Found Xcode workspace "MyApp.xcworkspace"
info Found booted iPhone 13
info Launching iPhone 13
info Building (using "xcodebuild -workspace MyApp.xcworkspace -configuration Debug -scheme MyApp -destination id=F9D05ED7-9D66-4017-B18C-FE9E6B107B6F")
▸ Running script 'Create Symlinks to Header Folders'
▸ Running script 'Create Symlinks to Header Folders'
▸ Running script 'Create Symlinks to Header Folders'
▸ Running script 'Start Packager'
▸ Linking MyApp

❌  ld: symbol(s) not found for architecture arm64



❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)


error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening MyApp.xcworkspace.
```

### Can you reproduce the bug?

Always

### Reproduction Steps

`react-native run-ios`

### Version

11.5.0

### What services are you using?

Local Database only

### Are you using encryption?

Yes

### Platform OS and version(s)

any

### Build environment

Which debugger for React Native: ..
sas

### Cocoapods version

11.5.0

### PR DESCRIPTION
**Pull request by kneth**
## What, How & Why?

Xcode 14 emits stubs for Objective C code which is incompatible with Xcode 13. See https://developer.apple.com/forums/thread/716965 for details.

This closes #5511

## ☑️ ToDos

* [x] 📝 Changelog entry
* ~[ ] 📝 `Compatibility` label is updated or copied from previous entry~
* ~[ ] 📝 Update `COMPATIBILITY.md`~
* [ ] 🚦 Tests
* ~[ ] 🔀 Executed flexible sync tests locally if modifying flexible sync~
* ~[ ] 📦 Updated internal package version in consuming `package.json`s (if updating internal packages)~
* [ ] 📱 Check the React Native/other sample apps work if necessary
* ~[ ] 📝 Public documentation PR created or is not necessary~
* ~[ ] 💥 `Breaking` label has been applied or is not necessary~

*If this PR adds or changes public API's:*
* ~[ ] typescript definitions file is updated~
* ~[ ] jsdoc files updated~

### CODE REVIEW

File: CMakeLists.txt [hunk 1]
```diff
@@ -81,6 +81,13 @@ if (NOT MSVC)
     endif()
 endif()
 
+if(APPLE)
+    if(NOT DEFINED CMAKE_JS_VERSION)
+        # https://developer.apple.com/forums/thread/716965
+        add_cxx_flag_if_supported(-fno-objc-msgsend-selector-stubs)
+    endif()
+endif()
+
```
Comment (fealebenpae) [inline CMakeLists.txt:90]: We want/need this on the `realm-js-ios` target in `src/ios/CMakeLists.txt` specifically because that's the one that compiled Objective-C code (`platform.mm`). No need to define it globally.

**Comment by kneth** [comment]
> if there would be a time we would want to add this back?

Good point. Once React Native specify Xcode 14 or later we can safely remove it again. I have created https://github.com/realm/realm-js/issues/5533 to track it.
