### ISSUE TITLE
Android: new Set( Realm.List ) fails with error undefined is not a function

### ISSUE THREAD

**Issue by a-golovanov** [realm/realm-js#1952]
## Goals

Construct standard js Set from Realm.List

## Expected Results

Realm.List should be treated the same way as a regular array, as it does on iOS and in nodejs.

## Actual Results

An exception is thrown - "undefined is not a function (evaluating `object[ITERATOR_SYMBOL]()`)"
<img width="287" alt="screen shot 2018-08-08 at 2 09 57 am" src="https://user-images.githubusercontent.com/19500149/43821996-5b58e9b4-9ab0-11e8-8414-90cccbdc3398.png">

## Steps to Reproduce

1. Create two models with one-to-many relation
2. Create an object that is `one` in the relation
3. Get it from DB
4. Try to create Set from the List property on the object

## Code Sample

```
import Realm from "realm";

const Location = {
    name: "Location",
    primaryKey: "id",
    properties: {
        id: "int",
    }
};

const UserProfile = {
    name: "UserProfile",
    primaryKey: "id",
    properties: {
        id: "int",
        locations: "Location[]",
    }
};

const realm = new Realm( {
    schema: [ Location, UserProfile ],
    inMemory: true
} );

realm.write( () => {
    realm.create( "UserProfile", { id: 1 } )
} );

const profile = realm.objectForPrimaryKey( "UserProfile", 1 );

new Set( profile.locations );

console.warn( "SUCCESS" );

realm.close();
```

## Version of Realm and Tooling

- Realm JS SDK Version: 2.13.0
- Node or React Native: RN 0.55.4
- Client OS & Version: Android 6.0
- Which debugger for React Native: None

## Additiona info

Code works fine on iOS 11.4 and node 8.11.1

**Comment by kneth** [comment]
Have you tried the suggestion in https://github.com/redux-saga/redux-saga/issues/54#issuecomment-346186605

**Comment by a-golovanov** [comment]
@kneth, thank you for the link! I haven't tried the suggested solution yet and I've worked around the issue with `new Set( Array.from( Realm.List ) )`, but I'll keep it in mind for future cases.

**Comment by kneth** [comment]
@a-golovanov Cool trick. I close the issue since we have other issues about making lists and results act more like arrays.
