### ISSUE TITLE
clang: error: linker command failed with exit code 1 (use -v to see invocation)

### ISSUE THREAD

**Issue by OceanHorn** [realm/realm-js#1620]
## Goals

Integrate react native to an exist iOS native App . 
run `npm i realm` to add `realm`.
run `react-native link realm`.

## Expected Results

Integrate `realm` successfully.

## Actual Results

From issues before, I can build RealmReact.xcodeproj now. But When build the total `*.xcworkspace` with Xcode, meet some errors.

#### Case 1:
Link `realm` by running `react-native link realm`, and build `*.xcworkspace`, met:
```
...
    /Users/OceanHorn/Library/Developer/Xcode/DerivedData/nmms-dqvajmmgqrijlhdzccxlxuxkvhkf/Build/Products/Debug-iphoneos/libRealmReact.a(sync_file-E8DF62E574C07A57.o)
duplicate symbol __ZN5realm15SyncFileManager20c_recovery_directoryE in:
    /Users/OceanHorn/Library/Developer/Xcode/DerivedData/nmms-dqvajmmgqrijlhdzccxlxuxkvhkf/Build/Products/Debug-iphoneos/libRealmReact.a(sync_file-E8DF62E574C07A57.o)
duplicate symbol __ZN5realm15SyncFileManager16c_sync_directoryE in:
    /Users/OceanHorn/Library/Developer/Xcode/DerivedData/nmms-dqvajmmgqrijlhdzccxlxuxkvhkf/Build/Products/Debug-iphoneos/libRealmReact.a(sync_file-E8DF62E574C07A57.o)
duplicate symbol __ZN5realm15SyncFileManager20c_metadata_directoryE in:
    /Users/OceanHorn/Library/Developer/Xcode/DerivedData/nmms-dqvajmmgqrijlhdzccxlxuxkvhkf/Build/Products/Debug-iphoneos/libRealmReact.a(sync_file-E8DF62E574C07A57.o)
...
duplicate symbol __ZN5realm19SyncMetadataManagerC2ENSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEEbNS_4util8OptionalINS1_6vectorIcS6_EEEE in:
    /Users/OceanHorn/Library/Developer/Xcode/DerivedData/nmms-dqvajmmgqrijlhdzccxlxuxkvhkf/Build/Products/Debug-iphoneos/libRealmReact.a(sync_metadata-231DCB0F6F3B43.o)
duplicate symbol __ZN5realm19SyncMetadataManagerC1ENSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEEbNS_4util8OptionalINS1_6vectorIcS6_EEEE in:
    /Users/OceanHorn/Library/Developer/Xcode/DerivedData/nmms-dqvajmmgqrijlhdzccxlxuxkvhkf/Build/Products/Debug-iphoneos/libRealmReact.a(sync_metadata-231DCB0F6F3B43.o)
duplicate symbol __ZN5realm16SyncUserMetadata14set_user_tokenENS_4util8OptionalINSt3__112basic_stringIcNS3_11char_traitsIcEENS3_9allocatorIcEEEEEE in:
    /Users/OceanHorn/Library/Developer/Xcode/DerivedData/nmms-dqvajmmgqrijlhdzccxlxuxkvhkf/Build/Products/Debug-iphoneos/libRealmReact.a(sync_metadata-231DCB0F6F3B43.o)
ld: 53 duplicate symbols for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

#### Case 2:
Link `realm` mannully, and build `*.xcworkspace`, met same error as case 1.

#### Case 3:
Do as case 1, then remove `libRealmReact.a` from `Target` -> `General` -> `Linked Frameworks and Libraries` and build. I can build normally, but when click to js module, met red screen:
```
Missing Realm constructor. Did you run "react-native link realm"? Please see https://realm.io/docs/javascript/latest/#missing-realm-constructor for troubleshooting
```
So, removing `libRealmReact.a` is not corrent.

#### Case 4:
Do as case 2, then remove as case 3. Same error occurs.

Is there any suggestions or solutions for this error?

## Steps to Reproduce

As described before.

## Code Sample

None.

## Version of Realm and Tooling
2.1.1

- Realm JS SDK Version: ? 
- Node or React Native: ? v9.3.0
- Client OS & Version: ? latest
- Which debugger for React Native: ? WebStorm

And, react native is supporting importing a dependency from pod with a `Podfile` file for iOS, is there any plan for `realm`?

**Comment by kneth** [comment]
To me, it looks like you end up with two versions of Realm (case 1 says `duplicate symbol`). I don't have a fullproof methods to avoid it. At least you have to ensure that Realm JS and Realm Cocoa are using the same version of Realm Core and Realm Sync.

**Comment by OceanHorn** [comment]
@kneth I solved by adding a podspec file and install realm with cocoapods for  realm version `2.1.1` and `2.0.13`. But i don't work on version `2.2.x`, I will try and give a PR.

**Comment by pedrobarros** [comment]
@OceanHorn, I'm facing the exact same problem! Could you please post your podspec file? Thanks!!

**Comment by kneth** [comment]
@OceanHorn Any updates?

**Comment by chriskinzel** [comment]
Same problem here, anyone ever figure out what @OceanHorn did?

**Comment by kneth** [comment]
Supporting pods is something we could be happy if the community can help with. Please :smile:

**Comment by bmunkholm** [comment]
Closing as outdated.
