### ISSUE TITLE
Google token string depreciated please use auth code object 

### ISSUE THREAD

**Issue by Haseebshah936** [realm/realm-js#5078]
### How frequently does the bug occur?

All the time

### Description

Uncaught (in promise) Error: `google(<tokenString>)` has been deprecated.  Please use `google(<authCodeObject>)`.
I have received this error. All tough I was following the original docs both for google one tap connect and realm. Did some digging and found that this error shows when creating realm credential for google. I am using the `realm web sdk with react`. This error is generating from `bundle.dom.es.js `at line 2386 in method `derivePayload`. If there is any solution or some has faced this issue before it will be grate if you can share the solution. The same issue can be recreated by using the code provided in the `realm web sdk google authentication code sample`. 

https://www.mongodb.com/docs/realm/web/authenticate/#std-label-web-google-onetap

### Can you reproduce the bug?

Yes, always

### Version

2.0.0

### What SDK flavour are you using?

Atlas App Services (auth, functions, etc.)

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

Mac

### Build environment

React

**Comment by kneth** [comment]
@Haseebshah936 

In order to make the API clear, we have moved from positional parameters to [named parameters](https://en.wikipedia.org/wiki/Named_parameter). From version 2.0.0 you should use

```js
const autoCode = ...;
const creds = Realm.Credentials.google({
  authCode
});
```

**Comment by Haseebshah936** [comment]
const googleAuth = React.useCallback(
    async (code) => {
      const credentials = Realm.Credentials.google(code);
      console.log(credentials);
      try {
        // Authenticate the user
        const user = await realmApp.logIn(credentials);
        // `App.currentUser` updates to match the logged in user
        console.assert(user.id === realmApp.currentUser.id);
        return user;
      } catch (err) {
        console.error("Failed to log in", err);
      }
    },
    [realmApp]
  );

// Google One Tap Login
const loadScript = (src) =>
    new Promise((resolve, reject) => {
      if (document.querySelector(`script[src="${src}"]`)) return resolve();
      const script = document.createElement("script");
      script.src = src;
      script.onload = () => resolve();
      script.onerror = (err) => reject(err);
      document.body.appendChild(script);
    });

  const googleButton = useRef(null);

// loading script for google oneTap and rendering google button

  useEffect(() => {
    const src = "https://accounts.google.com/gsi/client";
    const id =
      "Client Id ;)";

    loadScript(src)
      .then(() => {
        /*global google*/
        console.log(google);
        google.accounts.id.initialize({
          client_id: id,
          callback: handleCredentialResponse,
        });
        google.accounts.id.renderButton(googleButton.current, {
          theme: "filled_blue",
          size: "large",
        });
      })
      .catch(console.error);

    return () => {
      const scriptTag = document.querySelector(`script[src="${src}"]`);
      if (scriptTag) document.body.removeChild(scriptTag);
    };
  }, []);

// Call back function triggered when google button is pressed

  async function handleCredentialResponse(response) {
    console.log("Encoded JWT ID token: " + response.credential);
    googleAuth(response.credential);
  }



Here is my code which gave the error. I think I am already using this method. The code here was coming from google one tap login. I have also tested it against @react-oauth/google.

// @react-oauth/google.

const googleAuth = useGoogleLogin({
    flow: "auth-code",
    onSuccess: async ({ code }) => {
      console.log(code);
      const credentials = Realm.Credentials.google(code);
      realmApp
        .logIn(credentials)
        .then((user) => alert(`Logged in with id: ${user.id}`));
    },
    redirect_uri: "http://localhost:3000/home",
  });

**Comment by takameyer** [comment]
@Haseebshah936 Did the suggested change help?

**Comment by Haseebshah936** [comment]
Sorry for the delay in reply but no the suggested solution doesn't worked it returened realm auth. Quite frankly I didn't remember the exact response. But I will share it in a while.

**Comment by takameyer** [comment]
@Haseebshah936 If this doesn't work:
```typescript
const credentials = Realm.Credentials.google({ authCode: code })
```
try this:
```typescript
const credentials = Realm.Credentials.google({ idToken: code })
```

**Comment by jwing8** [comment]
I'm running into the same issue.  I tried changing the parameter from a string (which worked prior to 2.0) to an object, testing both authCode and idToken as properties, however I keep getting the following error:  TypeError: (intermediate value).google is not a function

The documentation stills refers to passing in a string in the example provided on https://www.mongodb.com/docs/realm/web/authenticate/#std-label-web-login-google

**Comment by Haseebshah936** [comment]
Sorry for the delay in reply.
I have received this error after trying idToken
error fetching info from OAuth2 provider (status 401) at MongoDBRealmError.fromRequestAndResponse 
and this when using authCode:
error exchanging access code with OAuth2 provider (status 401)   at MongoDBRealmError.fromRequestAndResponse

**Comment by takameyer** [comment]
Ok, we will investigate this further.  I'll update here when we have something to report.

**Comment by Haseebshah936** [comment]
ok

**Comment by jwing8** [comment]
I think the issue may have been introduced in 1.6.0 or later because I was able to get this working in 1.5.1 but none of the later versions.

**Comment by takameyer** [comment]
@Haseebshah936 The changes made to 2.0.0 are visible here: 
https://github.com/realm/realm-js/commit/8472cb0e3c6681b24f19a5d923554168d6a1dc7d#diff-ece863e03f42ffef7e48ed9ec9afb7386df3abf7022aea3c1552c7837fda6b75
Basically we are letting you decide from the application code which authentication string you want to set.  In your case, `idToken` should be the correct one.  

That being said, I don't see anything in our code that would cause you to start receiving authentication errors.  Perhaps there is an issue with the configuration.  Can you verify that everything is setup correctly in App Services?

@jwing8 Your error looks quite different than what is reported here.  Can you make a separate issue and show some example code, as well as what versions of `realm-web` you are using.

**Comment by takameyer** [comment]
We wrote a small test application that you can use as an example to authorize:
https://codesandbox.io/s/realm-web-google-auth-vanilla-ujkc0o

You can replace the app-id with yours.  If everything is properly configured, both in Atlas and in Google, it should work.

**Comment by Haseebshah936** [comment]
@takameyer  Here are the App services setting 
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/56692446/212493767-840162ee-c7fe-4b51-b824-6cb32cff11d1.png">
More over on trying the sandbox version you provided the google button disappears when i replaced the realm id in index.html with my app id. I tried adding the url to the app setting as allowed but it throughs error that the origin not allowed any idea about that would also be help full.

**Comment by takameyer** [comment]
@Haseebshah936 You will have to configure the request origins, both in atlas and in google dashboard, for the sandbox application (https://ujkc0o.csb.app/).  In any case, carefully review our [documentation](https://www.mongodb.com/docs/atlas/app-services/authentication/google/) on how to setup google authentication.

**Comment by Srujan1527** [comment]
@takameyer  @kneth @Haseebshah936  @timanglade  
can u explain how to get the auth code with a sample example

**Comment by matt2legit** [comment]
I've tried the idToken and authCode on web and no matter what I'm getting a 401 error.  What makes this even more bizarre is that it works just fine with the authCode in React Native.  The code's look similar on both, so I don't understand why it's not working on web.

**Comment by matt2legit** [comment]
I finally got it to work by turning on OpenID Connect and using the idToken.  

I still don't understand why the authCode doesn't work on web or why metadata doesn't save when it's available in the idToken.  As a work around, I used `jwt_decode` to extract it from the idToken and saved it to customData as suggested on another issues.

FWIW, I think most of the issues/improvements are needed server side and not with the realm-js library.  Where is the best place to provide that feedback?

**Comment by Srujan1527** [comment]
`You can pass redirectUri like below instead of authCode(If you don't have) 

        const redirectUri = "http://localhost:3000";

        const credentials = Realm.Credentials.google({
          redirectUrl: redirectUri,
        });
        console.log(credentials);
     

        app
          .logIn(credentials)
          .then((user) => alert(`Logged in with id:${user.id}`))
          .catch((err) => console.log(err));`

**Comment by jwing8** [comment]
> We wrote a small test application that you can use as an example to authorize: https://codesandbox.io/s/realm-web-google-auth-vanilla-ujkc0o
> 
> You can replace the app-id with yours. If everything is properly configured, both in Atlas and in Google, it should work.

This example helped me resolve my issue.  Apparently I wasn't destructuring the idToken properly, so user error on my part (no additional config or passing in of redirectUrl needed).  Thank you very much for providing the sandbox example.

**Comment by takameyer** [comment]
Closing since this is not an issue we can fix.  Google auth is not straightforward to implement and its easy to mess up.  If you are having issues, please consult our forums or talk to your MongoDB representative.
