### ISSUE TITLE
minor bug

### ISSUE THREAD

**Issue by serus22** [realm/realm-js#1193]
https://github.com/realm/realm-js/blob/c8e4dc39c09d5161347a4ef2d2d2f5d7e5564c92/react-native/android/src/main/java/io/realm/react/RealmReactPackage.java#L23

when i run build with latest stable react-native (0.47.1) i got this
i am using java 8

after removing this "@override" annotation, build succeeded

:realm:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
/home/matus/dev/testapp/node_modules/realm/android/src/main/java/io/realm/react/RealmReactPackage.java:18: error: method does not override or implement a method from a supertype
    @Override
    ^
Note: /home/matus/dev/testapp/node_modules/realm/android/src/main/java/io/realm/react/RealmReactModule.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error
:realm:compileReleaseJavaWithJavac FAILED

**Comment by serus22** [comment]
will be fixed by 1178
