### ISSUE TITLE
Missing prebuilds/node when using node v23

### ISSUE THREAD

**Issue by c100k** [realm/realm-js#6980]
### How frequently does the bug occur?

Always

### Description

I've just upgraded my codebase to node v23. After running `yarn install` and `yarn start`, my Node app using Realm does not start anymore saying `Cannot find module '/home/app/node_modules/realm/prebuilds/node/realm.node'`.

And indeed, `ls -la node_modules/realm/prebuilds` shows only `android` and `apple`.

When I switch back to node v22 and run `yarn install` and `yarn start` again, it works as `node_modules/realm/prebuilds` contains `android`, `apple` and `node.

### Stacktrace & log output

```shell
Error: Cannot find module '/home/app/node_modules/realm/prebuilds/node/realm.node'.
```

### Can you reproduce the bug?

Always

### Reproduction Steps

Assuming you have a project with `package.json` having `realm@12.14.1` as a dependency.

```sh
nvm use 22
rm -rf node_modules && yarn install
ls -la node_modules/realm/prebuilds # OK => contains android, apple and node

nvm use 23
rm -rf node_modules && yarn install
ls -la node_modules/realm/prebuilds # KO => contains android, apple but not node
```

### Version

12.14.1

### What services are you using?

Local Database only

### Are you using encryption?

Yes

### Platform OS and version(s)

macOS Sequoia

**Comment by brianomchugh** [comment]
FWIW I am on node@23.9.0 and and realm@12.11.0 and do not have this issue.

**Comment by Acetyld** [comment]
Same issue here

**Comment by Acetyld** [comment]
Is there any update on this?

**Comment by kraenhansen** [comment]
> Is there any update on this?

None. If you're a paying customer hitting this issue, please ensure you reach out via the official support channels.

Any help from the community investigating, debugging and fixing this would be highly appreaciated.

**Comment by matthesjh** [comment]
We have the same issue after upgrading `node` from 22.13.1 to 22.14.0. Updating the `prebuild-install` dependency of Realm to version 7.1.3 (see related [issue](https://github.com/prebuild/prebuild-install/pull/204)) fixed the problem for us. This can be done by running `npm update prebuild-install` and does not require an update of Realm.
